### ISSUE TITLE
Resumen apartado agilidad

### ISSUE THREAD

**Issue by mgarciap2490** [mgarciap2490/Ing_Gest_Poyectos#1]
La gestión ágil es útil en industrias con rápida evolución y productos abstractos, permitiendo ajustes y cambios en el desarrollo para mejorar continuamente el producto. Scrum es un marco de trabajo ágil que ayuda a lograr objetivos en empresas del conocimiento.

- De dónde venimos y por qué la agilidad se suele asociar con la informática
El conocimiento evoluciona con tesis, antítesis y síntesis. Los marcos ágiles surgieron como antítesis a la ingeniería del software.

- Procesos y gestión predictiva
La ingeniería del software surgió en 1968, pero en los años 90 fue cuestionada a favor de los marcos ágiles debido a la aplicabilidad limitada de la planificación predictiva en proyectos de software.

**Comment by antoniia0** [comment]
Resumen añadido a la Wiki
