### ISSUE TITLE
Resumen apartado Desmontando la gestión de proyectos

### ISSUE THREAD

**Issue by mgarciap2490** [mgarciap2490/Ing_Gest_Poyectos#2]
Para simplificar la gestión de proyectos, se pueden utilizar tres conceptos y dos modelos de gestión: desarrollo completo o incremental, trabajo secuencial o concurrente, y conocimiento basado en procesos o en personas. Scrum es un modelo ágil que utiliza desarrollo incremental, trabajo concurrente, conocimiento basado en personas y equipos autogestionados.

**Comment by antoniia0** [comment]
he modificado un poco el resumen

**Comment by antoniia0** [comment]
ya está añadido a la Wiki
