### ISSUE TITLE
Resumen apartado Diferenciando prácticas de principios y valores

### ISSUE THREAD

**Issue by mgarciap2490** [mgarciap2490/Ing_Gest_Poyectos#3]
Para trabajar con Scrum, es importante seguir el marco estándar descrito en los manuales, incluyendo roles, artefactos y eventos. Una vez que se logra un flujo iterativo, es posible adaptar y mejorar prácticas basándose en los principios y valores de Scrum y las características del proyecto o equipo. La segunda parte del manual se enfoca en cómo avanzar más allá de las prácticas iniciales.

**Comment by antoniia0** [comment]
resumen añadido a la Wiki
